# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'WAIS-IV PromptfkxUVR.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPlainTextEdit, QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(913, 493)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.PromptButton = QPushButton(self.centralwidget)
        self.PromptButton.setObjectName(u"PromptButton")
        self.PromptButton.setGeometry(QRect(200, 360, 100, 32))
        self.Input_FSIQ = QLineEdit(self.centralwidget)
        self.Input_FSIQ.setObjectName(u"Input_FSIQ")
        self.Input_FSIQ.setGeometry(QRect(100, 90, 113, 21))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 90, 58, 21))
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 140, 58, 21))
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Input_VCI = QLineEdit(self.centralwidget)
        self.Input_VCI.setObjectName(u"Input_VCI")
        self.Input_VCI.setGeometry(QRect(100, 140, 113, 21))
        self.Input_PRI = QLineEdit(self.centralwidget)
        self.Input_PRI.setObjectName(u"Input_PRI")
        self.Input_PRI.setGeometry(QRect(100, 170, 113, 21))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 170, 58, 21))
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Input_PSI = QLineEdit(self.centralwidget)
        self.Input_PSI.setObjectName(u"Input_PSI")
        self.Input_PSI.setGeometry(QRect(100, 230, 113, 21))
        self.Input_WMI = QLineEdit(self.centralwidget)
        self.Input_WMI.setObjectName(u"Input_WMI")
        self.Input_WMI.setGeometry(QRect(100, 200, 113, 21))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 200, 58, 21))
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 230, 58, 21))
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Input_SI = QLineEdit(self.centralwidget)
        self.Input_SI.setObjectName(u"Input_SI")
        self.Input_SI.setGeometry(QRect(330, 70, 113, 21))
        self.Input_BD = QLineEdit(self.centralwidget)
        self.Input_BD.setObjectName(u"Input_BD")
        self.Input_BD.setGeometry(QRect(330, 40, 113, 21))
        self.Input_DS = QLineEdit(self.centralwidget)
        self.Input_DS.setObjectName(u"Input_DS")
        self.Input_DS.setGeometry(QRect(330, 100, 113, 21))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(270, 100, 58, 21))
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(270, 130, 58, 21))
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Input_MR = QLineEdit(self.centralwidget)
        self.Input_MR.setObjectName(u"Input_MR")
        self.Input_MR.setGeometry(QRect(330, 130, 113, 21))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(270, 40, 58, 21))
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(270, 70, 58, 21))
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Input_AR = QLineEdit(self.centralwidget)
        self.Input_AR.setObjectName(u"Input_AR")
        self.Input_AR.setGeometry(QRect(330, 190, 113, 21))
        self.Input_SS = QLineEdit(self.centralwidget)
        self.Input_SS.setObjectName(u"Input_SS")
        self.Input_SS.setGeometry(QRect(330, 220, 113, 21))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(270, 220, 58, 21))
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(270, 250, 58, 21))
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Input_VC = QLineEdit(self.centralwidget)
        self.Input_VC.setObjectName(u"Input_VC")
        self.Input_VC.setGeometry(QRect(330, 160, 113, 21))
        self.Input_VP = QLineEdit(self.centralwidget)
        self.Input_VP.setObjectName(u"Input_VP")
        self.Input_VP.setGeometry(QRect(330, 250, 113, 21))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(270, 160, 58, 21))
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(270, 190, 58, 21))
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(270, 310, 58, 21))
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(270, 280, 58, 21))
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Input_CD = QLineEdit(self.centralwidget)
        self.Input_CD.setObjectName(u"Input_CD")
        self.Input_CD.setGeometry(QRect(330, 310, 113, 21))
        self.Input_IN = QLineEdit(self.centralwidget)
        self.Input_IN.setObjectName(u"Input_IN")
        self.Input_IN.setGeometry(QRect(330, 280, 113, 21))
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(530, 90, 321, 251))
        self.CopyButton = QPushButton(self.centralwidget)
        self.CopyButton.setObjectName(u"CopyButton")
        self.CopyButton.setGeometry(QRect(750, 360, 100, 32))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(40, 40, 58, 21))
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Input_Age = QLineEdit(self.centralwidget)
        self.Input_Age.setObjectName(u"Input_Age")
        self.Input_Age.setGeometry(QRect(100, 40, 113, 21))
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(530, 30, 221, 31))
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(690, 60, 161, 31))
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(640, 410, 261, 31))
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(530, 440, 371, 31))
        self.label_20.setCursor(QCursor(Qt.CursorShape.IBeamCursor))
        self.label_20.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_20.setWordWrap(False)
        self.label_20.setOpenExternalLinks(False)
        self.label_20.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextSelectableByMouse)
        MainWindow.setCentralWidget(self.centralwidget)
#if QT_CONFIG(shortcut)
        self.label.setBuddy(self.Input_FSIQ)
        self.label_2.setBuddy(self.Input_VCI)
        self.label_3.setBuddy(self.Input_PRI)
        self.label_4.setBuddy(self.Input_WMI)
        self.label_5.setBuddy(self.Input_PSI)
        self.label_6.setBuddy(self.Input_DS)
        self.label_7.setBuddy(self.Input_MR)
        self.label_8.setBuddy(self.Input_BD)
        self.label_9.setBuddy(self.Input_SI)
        self.label_10.setBuddy(self.Input_SS)
        self.label_11.setBuddy(self.Input_VP)
        self.label_12.setBuddy(self.Input_VC)
        self.label_13.setBuddy(self.Input_AR)
        self.label_14.setBuddy(self.Input_CD)
        self.label_15.setBuddy(self.Input_IN)
        self.label_16.setBuddy(self.Input_FSIQ)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.Input_Age, self.Input_FSIQ)
        QWidget.setTabOrder(self.Input_FSIQ, self.Input_VCI)
        QWidget.setTabOrder(self.Input_VCI, self.Input_PRI)
        QWidget.setTabOrder(self.Input_PRI, self.Input_WMI)
        QWidget.setTabOrder(self.Input_WMI, self.Input_PSI)
        QWidget.setTabOrder(self.Input_PSI, self.Input_BD)
        QWidget.setTabOrder(self.Input_BD, self.Input_SI)
        QWidget.setTabOrder(self.Input_SI, self.Input_DS)
        QWidget.setTabOrder(self.Input_DS, self.Input_MR)
        QWidget.setTabOrder(self.Input_MR, self.Input_VC)
        QWidget.setTabOrder(self.Input_VC, self.Input_AR)
        QWidget.setTabOrder(self.Input_AR, self.Input_SS)
        QWidget.setTabOrder(self.Input_SS, self.Input_VP)
        QWidget.setTabOrder(self.Input_VP, self.Input_IN)
        QWidget.setTabOrder(self.Input_IN, self.Input_CD)
        QWidget.setTabOrder(self.Input_CD, self.PromptButton)
        QWidget.setTabOrder(self.PromptButton, self.plainTextEdit)
        QWidget.setTabOrder(self.plainTextEdit, self.CopyButton)

        self.retranslateUi(MainWindow)
        self.CopyButton.clicked.connect(self.plainTextEdit.copy)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"K-WAIS-IV \ubd84\uc11d \ud504\ub86c\ud504\ud2b8 \uc0dd\uc131\uae30", None))
        self.PromptButton.setText(QCoreApplication.translate("MainWindow", u"\ud504\ub86c\ud504\ud2b8 \uc0dd\uc131", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"FSIQ", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"VCI", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"PRI", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"WMI", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"PSI", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"DS", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"MR", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"BD", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"SI", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"SS", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"VP", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"VC", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"AR", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"CD", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"IN", None))
        self.CopyButton.setText(QCoreApplication.translate("MainWindow", u"\ubcf5\uc0ac\ud558\uae30", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\uc5f0\ub839", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\ud544\uc694\ud55c \ubb38\uc7a5\uc744 \ucd94\uac00\ud558\uac70\ub098 \uc218\uc815\ud558\uc2e0 \ud6c4", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\ubcf5\uc0ac\ud558\uae30 \ubc84\ud2bc\uc744 \ub20c\ub7ec\uc8fc\uc138\uc694", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\ub9cc\ub4e0 \uc0ac\ub78c: \uacbd\uc0c1\ubd81\ub3c4\uad50\uc721\uccad \uc804\ubb38\uc0c1\ub2f4\uad50\uc0ac \ucd5c\uaddc\ud638", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Github: https://github.com/ghchoi48/WAIS-IV-Prompt-Generator", None))
    # retranslateUi

